### ISSUE TITLE
Tags for versions missing in the git repository

### ISSUE THREAD

**Issue by nixpanic** [gluster/libgfapi-python#11]
Hi,

`python-glusterfs-api.spec` contains a version number, but there are no versioned tags in the git repository. Could you create the tags for the versions that were released?

Thanks!

**Comment by prashanthpai** [comment]
Until now, we've never had any official releases. `python-glusterfs-api.spec` wasn't maintained either. Will tag a release soon. Plan to have some fixes merged and the github mirror synced properly before that.

**Comment by prashanthpai** [comment]
A signed tag v1.0 has now been created. Spec file will be update accordingly.
