### ISSUE TITLE
Why only one host passed to gfapi.Volume?

### ISSUE THREAD

**Issue by tantra35** [gluster/libgfapi-python#20]
in libgfapi docs say that fucntion `glfs_set_volfile_server` may by called multiple times (https://github.com/gluster/glusterfs/blob/master/api/src/glfs.h#L141-L192)

**Comment by prashanthpai** [comment]
@tantra35 Hi. Yes, that was overlooked. We will fix it.

**Comment by eLvErDe** [comment]
Hello,

I actually tried it with success. You only need to inherit from Volume class and overwrite mount method like this:

```
class FailoverGfsVolume(Volume):
    [...]
    def mount(self):
        [...]
        for x in self.host:
            ret = api.glfs_set_volfile_server(self.fs, decode_to_bytes(self.protocol),
                                              decode_to_bytes(x), self.port)
            if ret < 0:
                err = ctypes.get_errno()
                raise LibgfapiException("glfs_set_volfile_server(%s, %s, %s, "
                                        "%s) failed: %s" % (self.fs, self.protocol,
                                                            x, self.port,
                                                            os.strerror(err)))
        [...]
```

**Comment by abulkavs** [comment]
@tantra35 , when it's going to be fixed, since overwriting entire mount is not the best choice long term?

**Comment by prashanthpai** [comment]
This is being added. Patch: https://review.gluster.org/#/c/20597
