### ISSUE TITLE
ctype error

### ISSUE THREAD

**Issue by ghost** [gluster/libgfapi-python#5]
In [1]: from gluster import api
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-6da571987642> in <module>()
----> 1 from gluster import api

/usr/lib/python2.6/site-packages/gfapi-0.0.1-py2.6.egg/gluster/api.py in <module>()
    321                               ctypes.c_int)(('glfs_lseek', client))
    322
--> 323 glfs_read = ctypes.CFUNCTYPE(ctypes.c_ssize_t,
    324                              ctypes.c_void_p,
    325                              ctypes.c_void_p,

AttributeError: 'module' object has no attribute 'c_ssize_t'

OS: centos 6.5
python: 2.6.6

**Comment by nandajavarma** [comment]
This issue should be fixed in the latest commit https://github.com/gluster/libgfapi-python/commit/c9fedc64081e1504a1bbf88be5a5dcfb9fff3652
@cppking Have you pulled and tried recently?

**Comment by prashanthpai** [comment]
This has been fixed.
